
docker run -it -d \
  --label traefik.http.routers.fortunefinance.rule=Host\(\`fortunefinance.loan-pocket.com\`\) \
  --label traefik.http.routers.fortunefinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.fortunefinance.tls=true \
  --label traefik.http.routers.fortunefinance.service=fortunefinance-credit-http \
  --label traefik.http.services.fortunefinance-credit-http.loadbalancer.server.port=80 \
  --name fortunefinance \
  --network web \
  --restart always \
  --expose 80 \
  emasanga/mikoposoft_nack:may19 


   